version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb+srv://admin:wwwwww@petblog.vz5bmgj.mongodb.net/MTUCIpractise?retryWrites=true&w=majority&appName=PetBlog
    volumes:
      - ./backend:/app